// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stages.proto

package stages // import "github.com/yourhe/autotest/proto/stages"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type State int32

const (
	State_ok   State = 0
	State_fail State = 1
)

var State_name = map[int32]string{
	0: "ok",
	1: "fail",
}
var State_value = map[string]int32{
	"ok":   0,
	"fail": 1,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}
func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_stages_03b46e4978c4082f, []int{0}
}

type CreateStagesRequest struct {
	Stages               string   `protobuf:"bytes,1,opt,name=stages,proto3" json:"stages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStagesRequest) Reset()         { *m = CreateStagesRequest{} }
func (m *CreateStagesRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStagesRequest) ProtoMessage()    {}
func (*CreateStagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stages_03b46e4978c4082f, []int{0}
}
func (m *CreateStagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStagesRequest.Unmarshal(m, b)
}
func (m *CreateStagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStagesRequest.Marshal(b, m, deterministic)
}
func (dst *CreateStagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStagesRequest.Merge(dst, src)
}
func (m *CreateStagesRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStagesRequest.Size(m)
}
func (m *CreateStagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStagesRequest proto.InternalMessageInfo

func (m *CreateStagesRequest) GetStages() string {
	if m != nil {
		return m.Stages
	}
	return ""
}

type CreateStagesResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStagesResponse) Reset()         { *m = CreateStagesResponse{} }
func (m *CreateStagesResponse) String() string { return proto.CompactTextString(m) }
func (*CreateStagesResponse) ProtoMessage()    {}
func (*CreateStagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stages_03b46e4978c4082f, []int{1}
}
func (m *CreateStagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStagesResponse.Unmarshal(m, b)
}
func (m *CreateStagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStagesResponse.Marshal(b, m, deterministic)
}
func (dst *CreateStagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStagesResponse.Merge(dst, src)
}
func (m *CreateStagesResponse) XXX_Size() int {
	return xxx_messageInfo_CreateStagesResponse.Size(m)
}
func (m *CreateStagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStagesResponse proto.InternalMessageInfo

func (m *CreateStagesResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SearchStagesRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchStagesRequest) Reset()         { *m = SearchStagesRequest{} }
func (m *SearchStagesRequest) String() string { return proto.CompactTextString(m) }
func (*SearchStagesRequest) ProtoMessage()    {}
func (*SearchStagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stages_03b46e4978c4082f, []int{2}
}
func (m *SearchStagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchStagesRequest.Unmarshal(m, b)
}
func (m *SearchStagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchStagesRequest.Marshal(b, m, deterministic)
}
func (dst *SearchStagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchStagesRequest.Merge(dst, src)
}
func (m *SearchStagesRequest) XXX_Size() int {
	return xxx_messageInfo_SearchStagesRequest.Size(m)
}
func (m *SearchStagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchStagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchStagesRequest proto.InternalMessageInfo

func (m *SearchStagesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SearchStagesRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchStagesRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type SearchStagesResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Stages               *Stages  `protobuf:"bytes,3,opt,name=stages,proto3" json:"stages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchStagesResponse) Reset()         { *m = SearchStagesResponse{} }
func (m *SearchStagesResponse) String() string { return proto.CompactTextString(m) }
func (*SearchStagesResponse) ProtoMessage()    {}
func (*SearchStagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stages_03b46e4978c4082f, []int{3}
}
func (m *SearchStagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchStagesResponse.Unmarshal(m, b)
}
func (m *SearchStagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchStagesResponse.Marshal(b, m, deterministic)
}
func (dst *SearchStagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchStagesResponse.Merge(dst, src)
}
func (m *SearchStagesResponse) XXX_Size() int {
	return xxx_messageInfo_SearchStagesResponse.Size(m)
}
func (m *SearchStagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchStagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchStagesResponse proto.InternalMessageInfo

func (m *SearchStagesResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SearchStagesResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *SearchStagesResponse) GetStages() *Stages {
	if m != nil {
		return m.Stages
	}
	return nil
}

type UpdateStagesRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Raw                  string   `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateStagesRequest) Reset()         { *m = UpdateStagesRequest{} }
func (m *UpdateStagesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateStagesRequest) ProtoMessage()    {}
func (*UpdateStagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stages_03b46e4978c4082f, []int{4}
}
func (m *UpdateStagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStagesRequest.Unmarshal(m, b)
}
func (m *UpdateStagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStagesRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateStagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStagesRequest.Merge(dst, src)
}
func (m *UpdateStagesRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateStagesRequest.Size(m)
}
func (m *UpdateStagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStagesRequest proto.InternalMessageInfo

func (m *UpdateStagesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateStagesRequest) GetRaw() string {
	if m != nil {
		return m.Raw
	}
	return ""
}

type UpdateStagesResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateStagesResponse) Reset()         { *m = UpdateStagesResponse{} }
func (m *UpdateStagesResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateStagesResponse) ProtoMessage()    {}
func (*UpdateStagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stages_03b46e4978c4082f, []int{5}
}
func (m *UpdateStagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStagesResponse.Unmarshal(m, b)
}
func (m *UpdateStagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStagesResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateStagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStagesResponse.Merge(dst, src)
}
func (m *UpdateStagesResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateStagesResponse.Size(m)
}
func (m *UpdateStagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStagesResponse proto.InternalMessageInfo

func (m *UpdateStagesResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateStagesResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type RemoveStagesRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveStagesRequest) Reset()         { *m = RemoveStagesRequest{} }
func (m *RemoveStagesRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveStagesRequest) ProtoMessage()    {}
func (*RemoveStagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stages_03b46e4978c4082f, []int{6}
}
func (m *RemoveStagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveStagesRequest.Unmarshal(m, b)
}
func (m *RemoveStagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveStagesRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveStagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveStagesRequest.Merge(dst, src)
}
func (m *RemoveStagesRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveStagesRequest.Size(m)
}
func (m *RemoveStagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveStagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveStagesRequest proto.InternalMessageInfo

func (m *RemoveStagesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RemoveStagesResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveStagesResponse) Reset()         { *m = RemoveStagesResponse{} }
func (m *RemoveStagesResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveStagesResponse) ProtoMessage()    {}
func (*RemoveStagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stages_03b46e4978c4082f, []int{7}
}
func (m *RemoveStagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveStagesResponse.Unmarshal(m, b)
}
func (m *RemoveStagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveStagesResponse.Marshal(b, m, deterministic)
}
func (dst *RemoveStagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveStagesResponse.Merge(dst, src)
}
func (m *RemoveStagesResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveStagesResponse.Size(m)
}
func (m *RemoveStagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveStagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveStagesResponse proto.InternalMessageInfo

func (m *RemoveStagesResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Stages struct {
	Stages               []*Stage `protobuf:"bytes,1,rep,name=stages,proto3" json:"stages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stages) Reset()         { *m = Stages{} }
func (m *Stages) String() string { return proto.CompactTextString(m) }
func (*Stages) ProtoMessage()    {}
func (*Stages) Descriptor() ([]byte, []int) {
	return fileDescriptor_stages_03b46e4978c4082f, []int{8}
}
func (m *Stages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stages.Unmarshal(m, b)
}
func (m *Stages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stages.Marshal(b, m, deterministic)
}
func (dst *Stages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stages.Merge(dst, src)
}
func (m *Stages) XXX_Size() int {
	return xxx_messageInfo_Stages.Size(m)
}
func (m *Stages) XXX_DiscardUnknown() {
	xxx_messageInfo_Stages.DiscardUnknown(m)
}

var xxx_messageInfo_Stages proto.InternalMessageInfo

func (m *Stages) GetStages() []*Stage {
	if m != nil {
		return m.Stages
	}
	return nil
}

type Stage struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string               `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Actions              []*Action            `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	State                State                `protobuf:"varint,4,opt,name=state,proto3,enum=autotest.protobuf.State" json:"state,omitempty"`
	Line                 int32                `protobuf:"varint,5,opt,name=line,proto3" json:"line,omitempty"`
	Image                string               `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	StartAt              *timestamp.Timestamp `protobuf:"bytes,7,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                *timestamp.Timestamp `protobuf:"bytes,8,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	TimeElapsed          float64              `protobuf:"fixed64,9,opt,name=time_elapsed,json=timeElapsed,proto3" json:"time_elapsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Stage) Reset()         { *m = Stage{} }
func (m *Stage) String() string { return proto.CompactTextString(m) }
func (*Stage) ProtoMessage()    {}
func (*Stage) Descriptor() ([]byte, []int) {
	return fileDescriptor_stages_03b46e4978c4082f, []int{9}
}
func (m *Stage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stage.Unmarshal(m, b)
}
func (m *Stage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stage.Marshal(b, m, deterministic)
}
func (dst *Stage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stage.Merge(dst, src)
}
func (m *Stage) XXX_Size() int {
	return xxx_messageInfo_Stage.Size(m)
}
func (m *Stage) XXX_DiscardUnknown() {
	xxx_messageInfo_Stage.DiscardUnknown(m)
}

var xxx_messageInfo_Stage proto.InternalMessageInfo

func (m *Stage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Stage) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Stage) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *Stage) GetState() State {
	if m != nil {
		return m.State
	}
	return State_ok
}

func (m *Stage) GetLine() int32 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *Stage) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Stage) GetStartAt() *timestamp.Timestamp {
	if m != nil {
		return m.StartAt
	}
	return nil
}

func (m *Stage) GetEndAt() *timestamp.Timestamp {
	if m != nil {
		return m.EndAt
	}
	return nil
}

func (m *Stage) GetTimeElapsed() float64 {
	if m != nil {
		return m.TimeElapsed
	}
	return 0
}

type Action struct {
	Msg                  string               `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Command              string               `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	State                State                `protobuf:"varint,3,opt,name=state,proto3,enum=autotest.protobuf.State" json:"state,omitempty"`
	Line                 int32                `protobuf:"varint,4,opt,name=line,proto3" json:"line,omitempty"`
	StartAt              *timestamp.Timestamp `protobuf:"bytes,5,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                *timestamp.Timestamp `protobuf:"bytes,6,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	TimeElapsed          float64              `protobuf:"fixed64,7,opt,name=time_elapsed,json=timeElapsed,proto3" json:"time_elapsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_stages_03b46e4978c4082f, []int{10}
}
func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (dst *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(dst, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Action) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Action) GetState() State {
	if m != nil {
		return m.State
	}
	return State_ok
}

func (m *Action) GetLine() int32 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *Action) GetStartAt() *timestamp.Timestamp {
	if m != nil {
		return m.StartAt
	}
	return nil
}

func (m *Action) GetEndAt() *timestamp.Timestamp {
	if m != nil {
		return m.EndAt
	}
	return nil
}

func (m *Action) GetTimeElapsed() float64 {
	if m != nil {
		return m.TimeElapsed
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateStagesRequest)(nil), "autotest.protobuf.CreateStagesRequest")
	proto.RegisterType((*CreateStagesResponse)(nil), "autotest.protobuf.CreateStagesResponse")
	proto.RegisterType((*SearchStagesRequest)(nil), "autotest.protobuf.SearchStagesRequest")
	proto.RegisterType((*SearchStagesResponse)(nil), "autotest.protobuf.SearchStagesResponse")
	proto.RegisterType((*UpdateStagesRequest)(nil), "autotest.protobuf.UpdateStagesRequest")
	proto.RegisterType((*UpdateStagesResponse)(nil), "autotest.protobuf.UpdateStagesResponse")
	proto.RegisterType((*RemoveStagesRequest)(nil), "autotest.protobuf.RemoveStagesRequest")
	proto.RegisterType((*RemoveStagesResponse)(nil), "autotest.protobuf.RemoveStagesResponse")
	proto.RegisterType((*Stages)(nil), "autotest.protobuf.Stages")
	proto.RegisterType((*Stage)(nil), "autotest.protobuf.Stage")
	proto.RegisterType((*Action)(nil), "autotest.protobuf.Action")
	proto.RegisterEnum("autotest.protobuf.State", State_name, State_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StagesSvicClient is the client API for StagesSvic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StagesSvicClient interface {
	CreateStages(ctx context.Context, in *CreateStagesRequest, opts ...grpc.CallOption) (*CreateStagesResponse, error)
	GetStages(ctx context.Context, in *SearchStagesRequest, opts ...grpc.CallOption) (*CreateStagesResponse, error)
	ListStages(ctx context.Context, in *SearchStagesRequest, opts ...grpc.CallOption) (*CreateStagesResponse, error)
	UpdateStages(ctx context.Context, in *UpdateStagesRequest, opts ...grpc.CallOption) (*CreateStagesResponse, error)
	RemoveStages(ctx context.Context, in *CreateStagesRequest, opts ...grpc.CallOption) (*CreateStagesResponse, error)
}

type stagesSvicClient struct {
	cc *grpc.ClientConn
}

func NewStagesSvicClient(cc *grpc.ClientConn) StagesSvicClient {
	return &stagesSvicClient{cc}
}

func (c *stagesSvicClient) CreateStages(ctx context.Context, in *CreateStagesRequest, opts ...grpc.CallOption) (*CreateStagesResponse, error) {
	out := new(CreateStagesResponse)
	err := c.cc.Invoke(ctx, "/autotest.protobuf.StagesSvic/CreateStages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stagesSvicClient) GetStages(ctx context.Context, in *SearchStagesRequest, opts ...grpc.CallOption) (*CreateStagesResponse, error) {
	out := new(CreateStagesResponse)
	err := c.cc.Invoke(ctx, "/autotest.protobuf.StagesSvic/GetStages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stagesSvicClient) ListStages(ctx context.Context, in *SearchStagesRequest, opts ...grpc.CallOption) (*CreateStagesResponse, error) {
	out := new(CreateStagesResponse)
	err := c.cc.Invoke(ctx, "/autotest.protobuf.StagesSvic/ListStages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stagesSvicClient) UpdateStages(ctx context.Context, in *UpdateStagesRequest, opts ...grpc.CallOption) (*CreateStagesResponse, error) {
	out := new(CreateStagesResponse)
	err := c.cc.Invoke(ctx, "/autotest.protobuf.StagesSvic/UpdateStages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stagesSvicClient) RemoveStages(ctx context.Context, in *CreateStagesRequest, opts ...grpc.CallOption) (*CreateStagesResponse, error) {
	out := new(CreateStagesResponse)
	err := c.cc.Invoke(ctx, "/autotest.protobuf.StagesSvic/RemoveStages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StagesSvicServer is the server API for StagesSvic service.
type StagesSvicServer interface {
	CreateStages(context.Context, *CreateStagesRequest) (*CreateStagesResponse, error)
	GetStages(context.Context, *SearchStagesRequest) (*CreateStagesResponse, error)
	ListStages(context.Context, *SearchStagesRequest) (*CreateStagesResponse, error)
	UpdateStages(context.Context, *UpdateStagesRequest) (*CreateStagesResponse, error)
	RemoveStages(context.Context, *CreateStagesRequest) (*CreateStagesResponse, error)
}

func RegisterStagesSvicServer(s *grpc.Server, srv StagesSvicServer) {
	s.RegisterService(&_StagesSvic_serviceDesc, srv)
}

func _StagesSvic_CreateStages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagesSvicServer).CreateStages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autotest.protobuf.StagesSvic/CreateStages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagesSvicServer).CreateStages(ctx, req.(*CreateStagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StagesSvic_GetStages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchStagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagesSvicServer).GetStages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autotest.protobuf.StagesSvic/GetStages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagesSvicServer).GetStages(ctx, req.(*SearchStagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StagesSvic_ListStages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchStagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagesSvicServer).ListStages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autotest.protobuf.StagesSvic/ListStages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagesSvicServer).ListStages(ctx, req.(*SearchStagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StagesSvic_UpdateStages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagesSvicServer).UpdateStages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autotest.protobuf.StagesSvic/UpdateStages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagesSvicServer).UpdateStages(ctx, req.(*UpdateStagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StagesSvic_RemoveStages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagesSvicServer).RemoveStages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/autotest.protobuf.StagesSvic/RemoveStages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagesSvicServer).RemoveStages(ctx, req.(*CreateStagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StagesSvic_serviceDesc = grpc.ServiceDesc{
	ServiceName: "autotest.protobuf.StagesSvic",
	HandlerType: (*StagesSvicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStages",
			Handler:    _StagesSvic_CreateStages_Handler,
		},
		{
			MethodName: "GetStages",
			Handler:    _StagesSvic_GetStages_Handler,
		},
		{
			MethodName: "ListStages",
			Handler:    _StagesSvic_ListStages_Handler,
		},
		{
			MethodName: "UpdateStages",
			Handler:    _StagesSvic_UpdateStages_Handler,
		},
		{
			MethodName: "RemoveStages",
			Handler:    _StagesSvic_RemoveStages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stages.proto",
}

func init() { proto.RegisterFile("stages.proto", fileDescriptor_stages_03b46e4978c4082f) }

var fileDescriptor_stages_03b46e4978c4082f = []byte{
	// 682 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0xfe, 0xed, 0xc4, 0x4e, 0x33, 0x89, 0xfa, 0xa7, 0x1b, 0xab, 0xb8, 0x51, 0xa5, 0x06, 0x4b,
	0x94, 0xa8, 0x12, 0x76, 0x0f, 0x42, 0xa0, 0x72, 0x55, 0x10, 0xe2, 0x86, 0x2b, 0x07, 0x6e, 0xb8,
	0xa9, 0xb6, 0xf1, 0xc6, 0x5d, 0x11, 0x7b, 0x8d, 0x77, 0x13, 0x04, 0x15, 0x12, 0x42, 0xe2, 0x09,
	0x78, 0x34, 0xc4, 0x1b, 0xf0, 0x1a, 0x48, 0xc8, 0xbb, 0x76, 0xeb, 0x24, 0xee, 0x81, 0x4a, 0x70,
	0x55, 0xcf, 0xf4, 0x9b, 0xf9, 0x76, 0xbe, 0x39, 0x04, 0xda, 0x5c, 0xe0, 0x90, 0x70, 0x37, 0x49,
	0x99, 0x60, 0x68, 0x0d, 0x4f, 0x05, 0x13, 0x84, 0x0b, 0x65, 0x9f, 0x4c, 0xc7, 0xbd, 0xcd, 0x90,
	0xb1, 0x70, 0x42, 0x3c, 0x9c, 0x50, 0x0f, 0xc7, 0x31, 0x13, 0x58, 0x50, 0x16, 0xe7, 0x01, 0xbd,
	0xad, 0xfc, 0xbf, 0x05, 0xdc, 0x13, 0x34, 0x22, 0x5c, 0xe0, 0x28, 0x51, 0x00, 0xe7, 0x01, 0x74,
	0x9f, 0xa5, 0x04, 0x0b, 0x32, 0x94, 0x3c, 0x3e, 0x79, 0x37, 0x25, 0x5c, 0xa0, 0x75, 0x30, 0x15,
	0xb1, 0xad, 0xf5, 0xb5, 0x41, 0xd3, 0xcf, 0x2d, 0x67, 0x1b, 0xac, 0x79, 0x38, 0x4f, 0x58, 0xcc,
	0x09, 0x5a, 0x05, 0x9d, 0x06, 0x39, 0x56, 0xa7, 0x81, 0x33, 0x84, 0xee, 0x90, 0xe0, 0x74, 0x74,
	0x3a, 0x9f, 0x76, 0x01, 0x86, 0x2c, 0x30, 0x26, 0x34, 0xa2, 0xc2, 0xae, 0xf5, 0xb5, 0x81, 0xe1,
	0x2b, 0x23, 0x23, 0x67, 0xe3, 0x31, 0x27, 0xc2, 0xae, 0x4b, 0x77, 0x6e, 0x39, 0x0c, 0xac, 0xf9,
	0xa4, 0xd5, 0xe4, 0x59, 0x56, 0xc1, 0x04, 0x9e, 0xd8, 0xba, 0xca, 0x2a, 0x0d, 0xb4, 0x77, 0x5e,
	0x52, 0x46, 0xd6, 0xda, 0xdf, 0x70, 0x97, 0xc4, 0x74, 0xf3, 0xc4, 0x45, 0xb5, 0x8f, 0xa0, 0xfb,
	0x3a, 0x09, 0x96, 0xc4, 0x59, 0xe4, 0xeb, 0x40, 0x2d, 0xc5, 0xef, 0x25, 0x5b, 0xd3, 0xcf, 0x3e,
	0x9d, 0xc7, 0x60, 0xcd, 0x07, 0x5e, 0xf2, 0xd2, 0x0e, 0xd4, 0x22, 0x1e, 0x16, 0x91, 0x11, 0x0f,
	0x9d, 0x7b, 0xd0, 0xf5, 0x49, 0xc4, 0x66, 0x57, 0x53, 0x3a, 0x03, 0xb0, 0xe6, 0x61, 0x39, 0x41,
	0x9e, 0x50, 0xbb, 0x48, 0x78, 0x08, 0xa6, 0xc2, 0xa0, 0xdd, 0x52, 0x4f, 0x6b, 0x83, 0xd6, 0xbe,
	0x7d, 0x99, 0x00, 0xe7, 0xf5, 0xff, 0xd0, 0xc1, 0x90, 0x9e, 0xa5, 0x87, 0xf7, 0xa1, 0x15, 0x10,
	0x3e, 0x4a, 0x69, 0x92, 0x4d, 0x5b, 0x5e, 0x40, 0xd9, 0x85, 0x0e, 0xa0, 0x81, 0x47, 0x72, 0x14,
	0xed, 0x9a, 0xa4, 0xab, 0xd2, 0xfb, 0x48, 0x22, 0xfc, 0x02, 0x89, 0x5c, 0x30, 0xb8, 0xc0, 0x82,
	0xc8, 0xc6, 0xaf, 0x5e, 0xf6, 0x42, 0x41, 0x7c, 0x05, 0x43, 0x08, 0xea, 0x13, 0x1a, 0x13, 0xdb,
	0x90, 0x8d, 0x96, 0xdf, 0x59, 0xf7, 0x69, 0x84, 0x43, 0x62, 0x9b, 0xf2, 0x51, 0xca, 0x40, 0x0f,
	0x61, 0x85, 0x0b, 0x9c, 0x8a, 0x63, 0x2c, 0xec, 0x86, 0xec, 0x7f, 0xcf, 0x55, 0xbb, 0x71, 0x91,
	0xfa, 0x55, 0xb1, 0x1b, 0x7e, 0x43, 0x62, 0x8f, 0x44, 0x36, 0x34, 0x24, 0x0e, 0xb2, 0xa0, 0x95,
	0x6b, 0x83, 0x0c, 0x12, 0x07, 0x47, 0x02, 0xdd, 0x85, 0x76, 0xb6, 0x64, 0xc7, 0x64, 0x82, 0x13,
	0x4e, 0x02, 0xbb, 0xd9, 0xd7, 0x06, 0x9a, 0xdf, 0xca, 0x7c, 0xcf, 0x95, 0xcb, 0xf9, 0xaa, 0x83,
	0xa9, 0x4a, 0x5f, 0x6e, 0x18, 0xb2, 0xa1, 0x31, 0x62, 0x51, 0x84, 0xe3, 0x20, 0x97, 0xb5, 0x30,
	0x2f, 0xd4, 0xa9, 0xfd, 0x99, 0x3a, 0xf5, 0x92, 0x3a, 0x65, 0x1d, 0x8c, 0xdb, 0xe8, 0x60, 0xde,
	0x56, 0x87, 0xc6, 0x92, 0x0e, 0x3b, 0x1b, 0x72, 0xbc, 0x04, 0x41, 0x26, 0xe8, 0xec, 0x6d, 0xe7,
	0x3f, 0xb4, 0x02, 0xf5, 0x31, 0xa6, 0x93, 0x8e, 0xb6, 0xff, 0xab, 0x0e, 0xa0, 0xe6, 0x76, 0x38,
	0xa3, 0x23, 0x74, 0x06, 0xed, 0xf2, 0xdd, 0x41, 0xdb, 0x15, 0xb5, 0x57, 0xdc, 0xb1, 0xde, 0xfd,
	0x6b, 0x71, 0x6a, 0x71, 0x9c, 0xde, 0x97, 0xef, 0x3f, 0xbf, 0xe9, 0x96, 0xf3, 0xbf, 0x37, 0xdb,
	0xf3, 0x32, 0xbc, 0xa7, 0x76, 0xe0, 0x50, 0xdb, 0x41, 0x1f, 0xa1, 0xf9, 0x82, 0x88, 0x2b, 0x98,
	0x2b, 0x4e, 0xdd, 0xcd, 0x99, 0x37, 0x25, 0xf3, 0x3a, 0xb2, 0x16, 0x98, 0xbd, 0x33, 0x1a, 0x7c,
	0x42, 0x33, 0x80, 0x97, 0x94, 0xff, 0x35, 0xf2, 0x3b, 0x92, 0x7c, 0x0d, 0x2d, 0x96, 0x8d, 0x3e,
	0x6b, 0xd0, 0x2e, 0x9f, 0xb0, 0x4a, 0xea, 0x8a, 0xe3, 0x78, 0x73, 0xea, 0x2d, 0x49, 0xbd, 0xd1,
	0xab, 0xac, 0x3b, 0x93, 0xfd, 0x0c, 0xda, 0xe5, 0x1b, 0xf7, 0x4f, 0x7b, 0xfe, 0x74, 0xf7, 0x8d,
	0x1b, 0x52, 0x71, 0x3a, 0x3d, 0x71, 0x47, 0x2c, 0xf2, 0x3e, 0xb0, 0x69, 0x7a, 0x4a, 0xbc, 0x22,
	0xaf, 0xfa, 0x39, 0xcd, 0xd1, 0x4f, 0xd4, 0x9f, 0x13, 0x53, 0x3a, 0x0f, 0x7e, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x39, 0xb7, 0x0a, 0xe6, 0xb2, 0x07, 0x00, 0x00,
}
